### ISSUE TITLE
Couldn't create Tagger error

### ISSUE THREAD

**Issue by lingvisa** [polm/fugashi#12]
```
/home/martin/nlp/my-env/spacy/bin/python /home/martin/nlp/spaCy/examples/ja_seg.py
Traceback (most recent call last):
  File "/home/martin/nlp/spaCy/examples/ja_seg.py", line 2, in <module>
    nlp = Japanese()  # use directly
  File "/home/martin/nlp/spaCy/spacy/language.py", line 173, in __init__
    make_doc = factory(self, **meta.get("tokenizer", {}))
  File "/home/martin/nlp/spaCy/spacy/lang/ja/__init__.py", line 111, in create_tokenizer
    return JapaneseTokenizer(cls, nlp)
  File "/home/martin/nlp/spaCy/spacy/lang/ja/__init__.py", line 84, in __init__
    self.tokenizer = try_fugashi_import().Tagger()
  File "fugashi/fugashi.pyx", line 229, in fugashi.Tagger.__init__
  File "fugashi/fugashi.pyx", line 176, in fugashi.GenericTagger.__init__
RuntimeError: Couldn't create Tagger. Maybe your arguments are invalid?
```

Hi, i installed fugashi from the source code and Python is 3.7. I am running it on Ubuntu 18, but got the above error message. Testing code:

```
from spacy.lang.ja import Japanese
nlp = Japanese()  # use directly
doc = nlp("りんごが大好きです。")
for token in doc:
    print(token.text, token.tag_)
```

**Comment by polm** [comment]
Thanks for the bug report, sorry you're having trouble. 

Do you have MeCab and Unidic installed?

**Comment by lingvisa** [comment]
Hi, do I need to install them seperately? I used to install mecab-
Python3.

**Comment by polm** [comment]
Yes, for now you need to install them separately. I'm working on a bundled release but can't say exactly when it'll be ready yet.

I'm not sure when you used it, but up until 0.7 `mecab-python3` also required MeCab to be installed separately. Versions after that don't require a separate MeCab or dictionary installation to work, but they include IPADic, which isn't supported by the Universal Dependencies schema spaCy uses (and is also unmaintained since 2007). 

Follow the instructions [here](https://www.dampfkraft.com/nlp/japanese-spacy-and-mecab.html) and you should be all set.

**Comment by lingvisa** [comment]
Hi, I followed your instructions to install both mecab and unidict
without error message. However, when I run the test, it gives an error on
my MacPro:

 mecab -D
param.cpp(69) [ifs] no such file or directory:
/usr/local/lib/mecab/dic/ipadic/dicrc

What's possible reason?

**Comment by lingvisa** [comment]
"AttributeError: 'fugashi.Node' object has no attribute 'pos'". Has this been tested in the release? Node doesn't set the 'pos' attribute.

**Comment by polm** [comment]
Hey, thanks for the update. Unfortunately that is a bug, and as you note `pos` is not on the standard Node objects.

I just made a new release, `0.1.9`, that fixes that issue and adds tests for it. Sorry for the trouble, let me know if the new release works.

**Comment by lingvisa** [comment]
Hi, it works perfectly. One question regarding one piece of code is this:
        for token, dtoken in zip(doc, dtokens):
            unidic_tags.append(dtoken.pos)
            pos = resolve_pos(dtoken)
            token.tag_ = pos
            token.lemma_ = dtoken.feature.lemma or dtoken.surface
Before 'pos' is assigned to token.tag_, both token.tag_ and token.pos_ are empty strings. After the assignment, both token.tag_ and token.pos_ are filled with values. Is this a Python feature that when one object attribute is changed, another one can be automatically affected?

**Comment by polm** [comment]
Glad to hear it works, thanks for the confirmation!

> Is this a Python feature that when one object attribute is changed, another one can be automatically affected?

This question is not really related to fugashi, but to give a quick answer, you can override attribute access in Python so that getting or setting an attribute causes stuff to happen, including changing other attributes. This can be done with the [property decorator](https://docs.python.org/3/library/functions.html#property), which is a builtin. 

Usually you don't need that and shouldn't use it, but to give an example, in Fugashi it's used to lazily instantiate the features tuple, which makes access faster if you're not using those. In spaCy tokens it's similarly used for efficiency purposes.

**Comment by lingvisa** [comment]
One more question regarding the use of "doc.user_data["unidic_tags"] = unidic_tags". Let's say if I have a full parser and want to integrate it into spaCy. In addition to pos and segmentation, how can I build the dependency relationships parsed by other tools into the spaCy's data structure? The "doc.user_data" way doesn't seem to work, because dependencies have to be relationships between token objects of spaCy. Any suggestion on how to go about this, if I have a dependency parser of Japanese?

**Comment by polm** [comment]
I haven't implemented a custom parser before, but you could use the [spaCy-StanfordNLP](https://github.com/explosion/spacy-stanfordnlp/blob/aa7371165778cc281536491f572eb3ff71f3c5f3/spacy_stanfordnlp/language.py#L160) implementation as a reference. Basically you get the dependencies, create a `Doc`, and use the `from_array` to override data. In general you can add sophisticated data to spaCy docs with a [pipeline component](https://spacy.io/usage/processing-pipelines#custom-components).

**Comment by lingvisa** [comment]
That's great to know the spaCy-StanfordNLP example. I appreciate a lot!

**Comment by polm** [comment]
Closing this since the bug was resolved, thanks again for the report.
