### ISSUE TITLE
python3.6 support

### ISSUE THREAD

**Issue by tamuhey** [polm/fugashi#14]
Hi, thank you for this great project!
I want to use fugashi with python3.6. 
Any plan to support it?

**Comment by polm** [comment]
Thanks for the PR, the changes look fine.

I'm not sure I want to put much effort into supporting these older versions, particularly 3.5, which hits end of life in just six months, but since the changes to support them aren't too drastic it's fine for now. (The lack of defaults in `namedtuple` in 3.6 was actually the original motivator for dropping support, see #11.)

There are some other changes that need to be released so I'll put this in a new release soon.
