### ISSUE TITLE
「私」 always pronounced as 「わたくし」

### ISSUE THREAD

**Issue by pedrominicz** [polm/fugashi#27]
More of a curiosity than an issue per se, but why 「私」 seems to always have 「わたくし」 as the reading?

**Comment by polm** [comment]
This is because わたし and わたくし have the same surface form and usage (pos/transitions), but わたくし has lower cost in UniDic. You can check the cost in `lex.csv` in the source UniDic distribution, it's the fourth column.

I've been asked about this several times before, but I'm not really sure why UniDic is like this. I am not sure how MeCab handles identical items in training; this could be an artifact of the implementation (わたくし sorts before わたし) or the BCCWJ could actually have more instances of わたくし than わたし (seems unlikely).

**Comment by pedrominicz** [comment]
Interesting. What exactly do you mean by "how MeCab handles identical items in training"? What techniques MeCab uses under the hood?

Also, an unrelated question, under your estimation, how many people use fugashi/`mecab-python3`/MeCab?

**Comment by polm** [comment]
> What exactly do you mean by "how MeCab handles identical items in training"? 

I don't know what MeCab does if you have dictionary entries that are the same. I need to look at the source for that. The training format is similar to the default command line output, but I'm not sure how it's used.

> Also, an unrelated question, under your estimation, how many people use fugashi/mecab-python3/MeCab?

No idea how many people use MeCab, there is no "community" like some projects have. You can kind of estimate the number of users for the Python packages via pepy:

https://pepy.tech/project/fugashi   20k/month
https://pepy.tech/project/mecab-python3   120k/month

But that includes mirrors, includes people redownloading, etc., so it's very approximate. I'm not aware of any better way to measure it.

**Comment by pedrominicz** [comment]
> No idea how many people use MeCab, there is no "community" like some projects have. You can kind of estimate the number of users for the Python packages via pepy:
> 
> https://pepy.tech/project/fugashi 20k/month
> https://pepy.tech/project/mecab-python3 120k/month
> 
> But that includes mirrors, includes people redownloading, etc., so it's very approximate. I'm not aware of any better way to measure it.

Ah, very interesting, it seems it is more people I would have initially imagined! Anyhow, thank you for the help!
