### ISSUE TITLE
Error when running with a lot of long sentences

### ISSUE THREAD

**Issue by bigredbug47** [polm/fugashi#35]
Hi @polm,

Thanks for creating the efficient library for Japanese Tokenize. 👏👏👏

I have occurred error when using the **fugashi** with the list of 1000 long sentences (avg. 50-100 words each sentence). ⚠⚠⚠

```
------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C', b'-r', b'/opt/conda/lib/python3.7/site-packages/unidic/dicdir/mecabrc', b'-d', b'/opt/conda/lib/python3.7/site-packages/unidic/dicdir', b'-Owakati']
error message: viterbi.cpp(54) [connector_->open(param)] connector.cpp(24) [cmmap_->open(filename, mode)] cannot open: /opt/conda/lib/python3.7/site-packages/unidic/dicdir/matrix.bin 
Exception in thread Thread-58:
Traceback (most recent call last):
    tagger = Tagger('-Owakati')
  File "fugashi/fugashi.pyx", line 313, in fugashi.fugashi.Tagger.__init__
  File "fugashi/fugashi.pyx", line 220, in fugashi.fugashi.GenericTagger.__init__
RuntimeError: Failed initializing MeCab
```
```
------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C', b'-r', b'/opt/conda/lib/python3.7/site-packages/unidic/dicdir/mecabrc', b'-d', b'/opt/conda/lib/python3.7/site-packages/unidic/dicdir', b'-Owakati']
error message: viterbi.cpp(50) [tokenizer_->open(param)] tokenizer.cpp(105) [property_.open(param)] char_property.cpp(82) [cmmap_->open(filename, "r")]  
```

Could you advise me how to solve this error? Thank you a lot. 🙏🙏🙏

Packages Version:
```
fugashi==1.1.0
mecab-python3==1.0.3
unidic==1.0.3
unidic-lite==1.0.8
```

**Comment by polm** [comment]
So that's a weird error, but the volume of data you describe is small and should not cause issues with MeCab. An example of too much data is an 80MB string.

More important is that the error happens when you're initializing MeCab, during mmap. It's not clear from the error but I suspect you're creating a tagger every time you analyze text? Something like this:

```
for text in texts:
    tagger = fugashi.Tagger("-Owakati")
    out = tagger.parse(text)
```

Don't do that, do this:

```
tagger = fugashi.Tagger()
for text in texts:
    tokens = tagger(text)
```

Generally you should only create one tagger per process. 

If that doesn't describe your issue, could you give a more complete code example, preferably something self-contained I can run to reproduce the issue? 

It's very weird that you would be able to open the file many times but not forever unless you're running out of memory. My understanding is that mmap should re-use memory, but I haven't tested that in MeCab.

**Comment by bigredbug47** [comment]
Thank you @polm 
I have created tagger every process, so after move it out of loop. Everything runs perfectly. 🙏🙏🙏
