### ISSUE TITLE
Multi-dictionary with fugashi.GenericTagger

### ISSUE THREAD

**Issue by kmining** [polm/fugashi#39]
Hello,
I want to create a custom dictionary and apply it to fugashi.
I succeeded in adding custom dictionary in mecab.

```
import MeCab 
import sys
m = MeCab.Tagger("-Ochasen -u /usr/local/lib/mecab/dic/userdic/mydic.dic")
text = m.parse("ユーザ設定")
print(text)
```
output
```
ユーザ設定	ユーザセッテイ	ユーザ設定	名詞-一般		
EOS
```

I am trying to use fugashi.GenericTagger to use the dictionary created in mecab for fugashi.
Like the mecab code above, I want to define both sysdic and userdic in fugashi.GenericTagger. 
Is it possible?
![image](https://user-images.githubusercontent.com/58632771/120885863-121ed700-c626-11eb-8a39-4af2df77f1f6.png)

**Comment by polm** [comment]
I think the problem here is that the system dictionary you are using in fugashi is not the same as the one you used to create your dictionary. Can you try adding an argument to the Tagger like `-d /path/to/system/dic`? 

I suspect this is happening because you are using a dictionary you installed separately when creating your user dictionary, but fugashi is using a dictionary installed via pip. 

If that doesn't work let me know.

Couple of other notes...

GenericTagger should work fine even if fields in user and system dictionary are very different, but I haven't tested it extensively. So if you have any other issues let me know.

Passing `-Ochasen` and then using `parseToNodeList` is kind of strange. I don't think it'll cause problems, but generally you don't need the `-Ochasen` if you're only using the node format. 

For simplicity, instead of `tagger.parseToNodeList(text)`, you can just use `tagger(text)`. They are the same.

**Comment by kmining** [comment]
Thanks it worked out well. Thank you. :)

**Comment by polm** [comment]
Thanks for confirming it worked, enjoy fugashi!
