### ISSUE TITLE
tokenization corner case

### ISSUE THREAD

**Issue by gmossessian** [polm/fugashi#41]
Hello,

I have encountered a corner case with MeCab and was hoping you could spend one or two sentences advising how to proceed -- whether to say "this is a known issue and it's hopeless" or "you are using the wrong dictionary" etc.

The following examples are with the full version of `unidic-2.3.0`

```
>>> t = fugashi.Tagger('-Owakati')
>>> t.parse('スムースストレッチコットンクルーネックT').split()
['スムースストレッチコットンクルーネック T']
>>> t.parse('スムースコットンフレンチスリーブロングワンピース').split()
['スムースコットンフレンチスリーブロングワンピース']
>>> katsu.romaji('スムースストレッチコットンクルーネックT')
'Sumuususutoretchikottonkuruunekku T'
```

And yet, sub-phrases seem to parse OK:

```
>>> t.parse('スムースストレッチ').split()
['スムース', 'ストレッチ']
>>> t.parse('コットンクルーネック').split()
['コットン', 'クルー', 'ネック']
```

Thank you!

**Comment by polm** [comment]
This is kind of a known issue and solving it is hard. I worked in ecommerce for years and saw cases like this and we never got a complete fix. I still remember a long discussion about some specific phrases that just wouldn't tokenize correctly, almost always coming out as large blobs like your examples.

Basically the issues are:

1. This never happens outside of ecommerce text. Writing this in daily life or any other kind of writing would be bizarre. So it's not often considered a problem.

2. Sequences of katakana words like this have a higher degree of ambiguity than normal Japanese, which is made worse by relatively low usage frequency (=less reference training data), so it's harder than general tokenization. 

3. MeCab creates virtual dictionary entries for unknown words with a fixed cost (maybe modified by length). For rare katakana words, their costs are already high, so the cost of actual dictionary words can end up higher than unks.

One thing you can do that will help in many cases is to download the source for a dictionary (say UniDic 2.1.2) and modify `char.def`. At the top of the file there's a section with columns labeled INVOKE, GROUP, and so on. Change the value of the INVOKE column for katakana from 1 to 0 and rebuild the dictionary. 

What that does it make it so that if words are found in the dictionary, the dictionary form will always be preferred to the unk. If all your words are in the dictionary this will do what you want. But if you have a made up brand name in there somewhere it's likely you'll get nonsense instead of one clump. 

Another thing you can do is try using the `-M` command line option to limit the max length of unks. It's around 25 by default, if I use 5 your first example text is tokenized correctly. But again that can cause weird side effects when you have actual unks. (Note that value has a bug and the actual limit is one more than the number you give.)

Anyway, there are options, but it's not easy. You can look at how MeCab handles unks or read about the implementation in Kudo's book (形態素解析の理論と実装), though that's Japanese only.

**Comment by polm** [comment]
Thanks for asking this usage question. Since this isn't a bug, and there's no real action to be taken on my part, I'm going to close it for now. If you have any other questions please feel free to open a new issue, or follow up here if some part of the answer didn't resovle the current issue.

**Comment by gmossessian** [comment]
Thank you @polm !
