### ISSUE TITLE
Windows Python 3.8.10 pip: 'mecab.h': No Such File or Directory

### ISSUE THREAD

**Issue by kdrkdrkdr** [polm/fugashi#56]
![image](https://user-images.githubusercontent.com/49074597/155484244-c221bfde-3424-4683-92f1-c4c99a7db84b.png)

![image](https://user-images.githubusercontent.com/49074597/155484368-ee3457dc-1eca-4760-b0d7-473eb66cba3c.png)

My Command line -> "pip install fugashi[unidic-lite]"

It's an error that happens on Windows. Is there any way to solve this problem?

**Comment by polm** [comment]
Please copy and paste text as text, do not paste screenshots of text.

This happens because you're not using a wheel, so it tries to build from source and fails because MeCab is not installed. This usually only happens if you're using 32bit Python on Windows. 

32bit Python on Windows is not supported, because as far as I am aware there is no merit to using it, and switching to 64bit is easy and has no downsides. If you are using it intentionally, let me know why and I can look at supporting it.

**Comment by polm** [comment]
Closing due to lack of response. Please feel free to reply if you need more help.
