### ISSUE TITLE
Supporting N-best Paths

### ISSUE THREAD

**Issue by teowenshen** [polm/fugashi#60]
Hi, 

Due to my use case which parses a lot of slangy, colloquial Japanese, the resulting best path often isn't the most sensible path. 

Hence, I need to extract N-best paths from the decoding lattice in order to have other paths to back off to in case my algorithm deems that the 1best isn't making sense. 

From what I noticed, currently fugashi's only supports for nbest returns a raw string. So, I have edited mecab.pxd and fugashi.py to return nbest results using the same namedtuples as 1best. Although I am using ["deprecated"](https://taku910.github.io/mecab/doxygen/classMeCab_1_1Tagger.html#aa52ae90664736f2e7caa5f9e7cc152a4) interfaces from MeCab, so far my add-on seems to be working. 

My questions are as follows:-
1. Will there be (or, is there) official nbest support for fugashi in the future? If yes, then I will keep tabs on the project. 
2. If you don't mind me using the deprecated methods of MeCab, I am interested to contribute to the project too. What kind of interface/design do you have in mind for the method?

**Comment by polm** [comment]
I'm not interested in doing any work on that feature myself, I've never used it. But if you've already written the code feel free to submit a PR and I can take a look at it. 

Similar to the current nbest (which was also added at user request), the method name should basically follow MeCab but be more Pythonic/reasonable. If you've handled the internal logic I think that should be the hard part rather than any interface details.

As far as being "deprecated", MeCab has basically been abandoned for like 9 years or so, and something like half the API (including the C API fugashi uses, if memory serves), is marked deprecated, so that's not really a concern.

**Comment by teowenshen** [comment]
Sure, please find [pull request](https://github.com/polm/fugashi/pull/61) made.

Please excuse the naming of the branch! I have another branch that works with the recommended Lattice class.

**Comment by polm** [comment]
Thanks! It might take me a bit but I'll take a look at it.

**Comment by polm** [comment]
This was addressed by #61.
