### ISSUE TITLE
How to use with Contemporary Spoken Japanese dictionary unidic?

### ISSUE THREAD

**Issue by ruisukun21** [polm/fugashi#64]
How can I use fugashi with the Contemporary Spoken Japanese dictionary unidic?
https://clrd.ninjal.ac.jp/unidic/back_number.html#unidic_csj

**Comment by polm** [comment]
You need to install the CSJ UniDic yourself (by downloading and unzipping it locally) and specify the path, just as you would with MeCab.

```
import fugashi
tagger = fugashi.Tagger("-d path/to/csj")
```

It looks like it uses the same format as CWJ UniDic so you can use the `Tagger` instead of the `GenericTagger`, but I haven't tested it extensively, so try switching if you run into trouble.

**Comment by ruisukun21** [comment]
Thank you for your reply!
I will try the flag -d.

unidic-py includes some desirable fixes and its github provides the scripts to perform them (https://github.com/polm/unidic-py/tree/master/extras).
I will try to apply these fixes too. 

For some scripts specify the path for each `fugashi.Tagger("-d path/to/csj")` can be inconvenient.
 
I will try to modified the values `unidic.DICDIR` by mocking.
I will report here after trying.

**Comment by polm** [comment]
Closing due to lack of response.
