### ISSUE TITLE
Cache in Windows Wheel build has issues

### ISSUE THREAD

**Issue by polm** [polm/fugashi#9]
Windows wheel builds are failing because curl finds the file it's downloading already exists and prompts for user input on whether to overwrite it. There's not a clear flag to force overwriting or not overwriting the existing file. 

I tried various methods to get around the prompt for input, such as deleting the file before downloading it or using a redirect, but they failed. Some of that was because it's bash on Windows and I'm not very familiar with how that works. 

@chezou Sorry, but could you take a look at this when you get a chance? I will take another look at it later but I'm kind of stumped right now.

One issue is it looks like the cache is restored successfully, but the download isn't skipped. Not sure why that would be the case...

**Comment by chezou** [comment]
The root cause is 
- checking cache is ignored https://github.com/polm/fugashi/blob/master/.github/workflows/windows.yml#L44
- unzip is conflicting not curl downloading

We have several workarounds:
1. Stop caching
2. Check directory existence before download and unzip mecab. If exists, we can skip them manually as bash command

**Comment by polm** [comment]
Thanks, since I realized the prompt is actually from unzip I just told unzip to overwrite for now, which fixed the problem at least.

Any idea why the cache is ignored?

**Comment by chezou** [comment]
I'm not sure why cache checking doesn't work. hmm

**Comment by polm** [comment]
OK, I guess I'll just take it out and close this for now.
